region = "ap-northeast-2"
s3-bucket = "s3-awx-bucket-newtest"
public_domain_name = "awx.co.kr"
private_domain_name = "awx.internal"
vpc-tagname = "VPC-awx"
keypair_name = "Keypair-awx"
keypair_file = "./keys/ec2-public-key.pem"
